# render.yaml
services:
  - type: web
    name: gambit-backend
    env: docker
    plan: starter
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true